churchmembers/urls.py
from django.conf.urls import *
from churchmembers.models import Family
from churchmembers.views import PersonDetail, PersonList
from django.views.generic import ListView, DetailView

urlpatterns = patterns('churchmembers.views',
    url(r'^update/$',
        view='family_info_form',
        name='membership_family_edit',
       ),
    url(r'^edit/(?P<username>[-\w]+)$',
         view='person_edit',
         name='membership_person_edit',
       ),
)

urlpatterns += patterns('',
    (r'^(members|friends)/(?P<username>[-\w]+)/$', PersonDetail.as_view()),
    (r'^(members|friends)/$', PersonList.as_view()),
    (r'^$', ListView.as_view(
        model=Family,
        context_object_name="family_list",
        queryset=Family.objects.all().exclude(status=0).order_by('name', 'slug'),
        template_name="family_list.html"
    )),
    (r'^(?P<slug>[-\w]+)/$', DetailView.as_view(
        model=Family,
        context_object_name="family",
        queryset=Family.objects.all().exclude(status=0).order_by('name', 'slug'),
        template_name="family_detail.html"
    )),
)

churchmembers/models.py
from django.db import models
from django.db.models import permalink
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import Group
from localflavor.us.models import PhoneNumberField, USStateField
from autoslug import AutoSlugField


class Person(models.Model):
    """Person model"""
    STATUS_CHOICES = (
        (0, 'Removed'),
        (1, 'Member'),
        (2, 'Friend'),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, primary_key=True)
    status = models.IntegerField(_('status'), choices=STATUS_CHOICES, default=2)
    family = models.ForeignKey('churchmembers.Family', blank=True, null=True, limit_choices_to={'status':1})
    head_of_household = models.BooleanField(_('Head of Household'), default=False, 
                                            help_text=_("Check if user is the family's head of household. There can only be one."))
    contact = models.ForeignKey('churchmembers.Contact', blank=True, null=True)
    notes = models.TextField(blank=True, help_text=_("Notes should not be made public"))
    photo = models.FileField(upload_to='member_photos', blank=True, help_text=_('An image that will be used as a thumbnail.'))

    class Meta:
        unique_together = (("family", "head_of_household"),)

    def __unicode__(self):
        if self.status == 1:
            return '{0} membership information'.format(self.user.get_full_name())
        else:
            return '{0} information'.format(self.user.get_full_name())

    @permalink
    def get_absolute_url(self):
        return ('profile_detail', None, {'username': self.user.username})

    @property
    def primary_contact(self):
        if self.contact is not None and self.contact.primary is True:
            return self.contact
        elif self.family is not None and self.family.contact is not None:
            return self.family.contact
        else:
            return ''


class Family(models.Model):
    """Family model"""
    STATUS_CHOICES = (
        (0, 'Inactive'),
        (1, 'Active'),
    )
    name = models.CharField(max_length=256)
    slug = AutoSlugField(populate_from='name', unique=True)
    contact = models.ForeignKey('churchmembers.Contact', blank=True, null=True)
    status = models.IntegerField(_('status'), choices=STATUS_CHOICES, default=1)
    notes = models.TextField(blank=True)
    photo = models.FileField(upload_to='family_photos', blank=True, 
                             help_text=_('An image that will be used as a thumbnail.'))

    class Meta:
        verbose_name_plural = 'families'

    def __unicode__(self):
        return '{0} family'.format(self.name)

    @property
    def head_of_household(self):
        try:
            head_of_household = self.person_set.get('head_of_household' is True)
        except self.DoesNotExist:
            head_of_household = ''
        return head_of_household

    @permalink
    def get_absolute_url(self):
        return ('family_detail', None, {'slug': self.slug})


class Member(models.Model):
    """Member model"""
    METHOD_CHOICES = (
        (1, 'Baptism'),
        (2, 'Letter'),
        (3, 'Other'),
    )
    person = models.OneToOneField(Person, primary_key=True)
    date_joined = models.DateField(blank=True, null=True)
    method = models.IntegerField(_('method'), choices=METHOD_CHOICES, default=1, 
                                 help_text=_("How was membership confirmed"))
    lettering_church = models.CharField(_('Church Name'), blank=True, null=True, max_length=320, 
                                        help_text=_("If method was by letter, please provide the name of the church supplying letter"))
    date_baptised = models.DateField(blank=True, null=True)
    conversion_story = models.TextField(blank=True, null=True)

    class Meta:
        permissions = (
              ("view_data", "Can view member data"),
        )


class Contact(models.Model):
    """Contact information model"""
    address = models.CharField(max_length=256, blank=True)
    city = models.CharField(max_length=128, blank=True)
    state = USStateField(blank=True, default='TX')
    zip_code = models.CharField(_('zip'), max_length=10, blank=True)
    mobile = PhoneNumberField(_('mobile phone'), blank=True)
    home_phone = PhoneNumberField(_('home phone'), blank=True)
    email = models.EmailField(_('public email'), max_length=254, blank=True)
    website = models.URLField(max_length=256, blank=True)
    primary = models.BooleanField(help_text=_('Primary contact information'), default=False)

    def __unicode__(self):
        return '{0}, {1}, {2}  {3}'.format(self.address, self.city, self.state, self.zip)


class Office(models.Model):
    """Office model"""
    STATUS_CHOICES = (
        (0, 'Inactive'),
        (1, 'Active'),
    )
    title = models.CharField(max_length=256)
    slug = AutoSlugField(populate_from='title', unique=True)
    status = models.IntegerField(_('status'), choices=STATUS_CHOICES, default=1)
    office_responsibilities = models.TextField(blank=True)
    notes = models.TextField(blank=True)
    members = models.ManyToManyField(Person, through='churchmembers.OfficeHolder')

    def __unicode__(self):
        return '{0}'.format(self.title)

    @permalink
    def get_absolute_url(self):
        return ('office_detail', None, {'slug': self.slug})


class OfficeHolder(models.Model):
    """OfficeHolders model with is through model for Office"""
    office = models.ForeignKey(Office)
    person = models.ForeignKey(Person)
    official_photo = models.FileField(upload_to='officer_photos', blank=True, 
                                      help_text=_('An image that will be used as a thumbnail.'))
    start_date = models.DateField(blank=True, null=True)
    ordained = models.BooleanField(help_text=_("Was an Ordaination performed for this office"), default=False)

    def __unicode__(self):
        return '{0}, {1}'.format(self.person.user.get_full_name(), self.office.title)

churchmembers/templates/churchmembers/base_members.html
{% extends "base.html" %}

{% block app_label %}{% endblock %}

{% block body_class %}family{% endblock %}

{% block rightrail %}
{% load blog tagging_tags thumbnail %}
<div class="right_rail">
   {% block rightrailcontent %}
   {% if family.photo %}<img src="{{ MEDIA_URL }}{{ family.photo.url|thumbnail:"200" }}" alt="{{ family.name }} family" width="200px" />
   <p class="mug_caption">{{ family.name }} family</p>{% endif %}
   {% endblock %}
  {% tag_cloud_for_model churchmembers.Family as family_tags with steps=9 min_count=1 distribution=log %}
  {% if famiy_tags %}
	<h2>Family tags</h2>
	<p class="tag_cloud">{% for tag in family_tags %}<span class="tag-{{tag.font_size }}"><a href="/family/tags/{{tag.name|slugify }}/">{{tag.name}}</a></span>{% endfor %}<span class="clr"></span></p>
  {% endif %}

</div>
{% endblock %}

churchmembers/templates/churchmembers/family_detail.html
{% extends "churchmembers/base_members.html" %}

{% block title %}Church Family: {{ object.name }}{% endblock %}
{% block body_id %}family_detail_page{% endblock %}

{% load i18n %}

{% block headline %}
  <h2>{{ object.name }}</h2>
{% endblock %}


{% block content %}
  {% load blog markup comments inlines %}
  <div class="main_content">
  {% with object as family %}
  {% ifequal family.status 1 %}
    {% if family.member_set.all %}<h3>Family members:</h3><ul>{% for member in family.member_set.all %}<li><a href="{{ member.profile.get_absolute_url }}">{{ member.profile.user.get_full_name }}</a></li>{% endfor %}</ul>{% endif %}
    {% if family.address or family.address2 or family.city or family.state or family.zip %}
    <h3>Address:</h3>
    <p>
    {% if family.address %}{{ family.address }}{% endif %}
    {% if family.address2 %}<br />{{ family.address2 }}{% endif %}
    {% if family.city %}<br />{{ family.city }}, {% endif %}
    {% if family.state %}{{ family.state }}{% endif %}
    {% if family.zip %}  {{ family.zip }}{% endif %}
    </p>
    {% endif %}
    {% if family.phone1 or family.phone2 or family.email or family.website %}
    <h3>Phone and Internet:</h3>
    <ul>
    {% if family.phone1 %}<li>{{ family.phone1 }}</li>{% endif %}
    {% if family.phone2 %}<li>{{ family.phone2 }}</li>{% endif %}
    {% if family.email %}<li>{{ family.email }}</li>{% endif %}
    {% if family.website %}<li>{{ family.website }}</li>{% endif %}
    </ul>
    {% endif %}
    {% ifequal user.get_profile.member.family family %}<p><a href="{% url family_form %}">Edit your family information</a></p>{% endifequal %} 

  {% else %}
  <p>No family information available</p>
  {% endifequal %}
  {% endwith %}
  </div>
{% endblock %}

{% block rightrailcontent %}{% load tagging_tags %}
  {% load thumbnail %}
  {% if object.photo %}<img src="{{ MEDIA_URL }}{{ object.photo.url|thumbnail:"200" }}" alt="{{ object.name }} family" width="200px" />
  <p class="mug_caption">{{ object.name }} family</p>{% endif %}
  {{ block.super }}
  {% tags_for_object object as tag_list %}
  {% if tag_list %}
  <h2>Related tags:</h2>
  <p class="inline_tag_list">
  {% for tag in tag_list %}
  <a href="{{ tag|slugify }}/">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
  {% endfor %}
  </p>
  {% endif %}
{% endblock %}

churchmembers/templates/churchmembers/family_list.html
{% extends "churchmembers/base_members.html" %}

{% block title %}Church Families{% endblock %}
{% block body_id %}family_list_page{% endblock %}

{% load i18n %}

{% block headline %}
  <h2 class="content_headline">Brentwood Hills Families</h2>
{% endblock %}


{% block content %}
  {% load blog markup comments inlines thumbnail %}
  {% for family in object_list %}
      {% ifequal family.status 1 %}
      <div class="family_item{% if forloop.counter0|divisibleby:"2" %} clr{% endif %}" id="family-{{ family.id }}">
        <h3><a href="{{ family.get_absolute_url }}">{{ family.name }} Family</a></h3>
        {% if family.photo %}<img src="{{ MEDIA_URL }}{{ family.photo.url|thumbnail:"200" }}" alt="{{ family.name }} family" width="200px" />{% endif %}
        {% if family.member_set.all %}<h4>Family members:</h4>
        <ul>{% for member in family.member_set.all %}<li><a href="{{ member.profile.get_absolute_url }}">{{ member.profile.user.get_full_name }}</a></li>{% endfor %}</ul>{% endif %}
        {% if family.address or family.address2 or family.city or family.state or family.zip %}
        <h4>Address:</h4>
        <ul>
        {% if family.address %}<li>{{ family.address }}</li>{% endif %}
        {% if family.address2 %}<li>{{ family.address2 }}</li>{% endif %}
        {% if family.city %}<li>{{ family.city }}, {{ family.state }}  {{ family.zip }}</li>{% endif %}
        </ul>
        {% endif %}
        {% if family.phone1 or family.phone2 or family.email or family.website %}
        <h4>Numbers:</h4>
        <ul>
        {% if family.phone1 %}<li>{{ family.phone1 }}</li>{% endif %}
        {% if family.phone2 %}<li>{{ family.phone2 }}</li>{% endif %}
        {% if family.email %}<li>{{ family.email }}</li>{% endif %}
        {% if family.website %}<li>{{ family.website }}</li>{% endif %}
        </ul>
        {% endif %}
      </div>
      {% endifequal %}
  {% endfor %}
{% endblock %}

{% block rightrailcontent %}
  <h2 class="content_headline">Families</h2>
  <ul>
  {% for family in object_list %}
    <li><a href="{{ family.get_absolute_url }}">{{ family.name }} family</a></li>
  {% endfor %}
  </ul>
{% endblock %}

churchmembers/templates/churchmembers/person_detail.html
{% extends "churchmembers/base_members.html" %}

{% block title %}{{ person.user.get_full_name }}{% endblock %}
{% block body_id %}person_detail_page{% endblock %}

{% load i18n %}

{% block headline %}
  <h2>{{ person.user.get_full_name }}</h2>
{% endblock %}


{% block content %}
  {% load blog markup comments inlines %}
  <div class="main_content">
    {% if person.address or person.city or person.state or person.zip %}
    <h3>Address:</h3>
    <p>
    {% if person.address %}{{ person.address }}{% endif %}
    {% if person.city %}<br />{{ person.city }}, {% endif %}
    {% if person.state %}{{ person.state }}{% endif %}
    {% if person.zip %}  {{ person.zip }}{% endif %}
    </p>
    {% endif %}
    {% with person.get_primary_contact as contact %}
    {% if contact.home_phone or contact.mobile or contact.email or contact.website %}
    <h3>Phone and Internet:</h3>
    <ul>
    {% if contact.home_phone %}<li>{{ contact.home_phone }}</li>{% endif %}
    {% if contact.mobile %}<li>{{ contact.mobile }}</li>{% endif %}
    {% if contact.email %}<li>{{ contact.email }}</li>{% endif %}
    {% if contact.website %}<li>{{ contact.website }}</li>{% endif %}
    </ul>
    {% endif %}
    {% ifequal user.person person %}<p><a href="{% url person_edit %}">Edit your contact information</a></p>{% endifequal %} 
    {% endwith %}
  </div>
{% endblock %}

churchmembers/templates/churchmembers/person_list.html
{% extends "churchmembers/base_members.html" %}

{% block title %}Church {{ Type }}{% endblock %}
{% block body_id %}person_list_page{% endblock %}

{% load i18n %}

{% block headline %}
  <h2 class="content_headline">{{ site.name }} {{ type|title }}</h2>
{% endblock %}


{% block content %}
  {% load blog markup comments inlines thumbnail %}
  {% for person in person_list %}
      <div class="item{% if forloop.counter0|divisibleby:"2" %} clr{% endif %}" id="user-{{ user.id }}">
        <h3><a href="{{ person.get_absolute_url }}">{{ person.user.get_full_name }}</a></h3>
        {% if person.photo %}<img src="{{ MEDIA_URL }}{{ person.photo.url|thumbnail:"200" }}" alt="{{ person.user.get_full_name }}" width="200px" />{% endif %}
        {% with person.get_primary_contact as contact %}
        {% if contact.address or contact.city %}
        <h4>Address:</h4>
        <ul>
        {% if contact.address %}<li>{{ contact.address }}</li>{% endif %}
        {% if contact.city %}<li>{{ contact.city }}, {{ contact.state }}  {{ contact.zip }}</li>{% endif %}
        </ul>
        {% endif %}
        {% if contact.mobile or contact.home_phone or contact.email or contact.website %}
        <h4>Numbers:</h4>
        <ul>
        {% if contact.home_phone %}<li>{{ contact.home_phone }}</li>{% endif %}
        {% if contact.mobile %}<li>{{ contact.mobile }}</li>{% endif %}
        {% if contact.email %}<li>{{ contact.email }}</li>{% endif %}
        {% if contact.website %}<li>{{ contact.website }}</li>{% endif %}
        </ul>
        {% endif %}
        {% endwith %}
      </div>
  {% endfor %}
{% endblock %}

churchmembers/templates/churchmembers/profile_form.html
{% extends "base.html" %}

{% block body_class %}profiles_form{% endblock %}


{% block title %}Profile form{% endblock %}


{% block content_title %}
  <h2>Update profile form</h2>
{% endblock %}



{% block content %}
  {% load thumbnail %}
  <form action="{% url membership_profile_edit object.user.username %}" method="post" enctype="multipart/form-data" class="profile_form">{% csrf_token %}
    {% if object.mugshot %}<div class="member_photo right_rail"><img src="{{ MEDIA_URL }}{{ object.mugshot.url|thumbnail:"200" }}" alt="profile photo" width="200px" /></div>{% endif %}
    <table>
      {{ user_form.as_table }}
      {{ profile_form.as_table }}
    </table>

    <div>
      <h4>Membership Information</h4>
      {% if object.member.photo %}<div class="member_photo right_rail"><img src="{{ MEDIA_URL }}{{ object.member.photo.url|thumbnail:"200" }}" alt="member photo" width="200px" /></div>{% endif %} 
      {# member_formset.management_form #}

      <table class="service">
        {% for field in member_form %}
          {% if not field.is_hidden %}
          {% if field.errors %}<tr><td columnwidth=2>{{ field.errors }}</td></tr>{% endif %}
          <tr>
           {% ifequal field.name "family" %}<th>{{ field.label_tag }}</th><td>{{ field }}{% if not object.member.family %} <span><a href="{% url family_form %}">Create a new family</a>, if not listed</span>{% endif %}</td>
           {% else %}
            <th>{{ field.label_tag }}</th> <td>{{ field }}</td>
           {% endifequal %}
          </tr>
          {% else %}
            {{ field }}
          {% endif %}
        {% endfor %}
      </table>
    </div>

    
    <div>
      <h4>Other profiles <small>(e.g. Flickr, Twitter, etc.)</small></h4>
      {{ service_formset.management_form }}
      
      {% for form in service_formset.forms %}
      <table class="service">
        {{ form }}
      </table>
      {% endfor %}
      
      <p class="quiet">To add more services than displayed save and continue editing.</p>
    </div>
    <div>
      <h4>Personal links <small>(Example: Your blog, you personal site, etc.)</small></h4>
      {{ link_formset.management_form }}
      
      {% for form in link_formset.forms %}
      <table class="link">
        {{ form }}
      </table>
      {% endfor %}
      
      <p class="quiet">To add more links than displayed save and continue editing.</p>
    </div>
    
    <p><input class="button" type="submit" value="Save"></p>
  </form>
{% endblock %}

churchmembers/templates/churchmembers/update_family_info.html
{% extends "churchmembers/base_members.html" %}

{% block title %}Church Family: {{ object.name }}{% endblock %}
{% block body_id %}family_detail_page{% endblock %}

{% load i18n %}

{% block headline %}
  <h2>Edit family information</h2>
{% endblock %}


{% block content %}
  {% load blog markup comments inlines %}
  <form action="." method="post">{% csrf_token %}
    <div>
      <table>
      {{ family_form.as_table }}
      </table>
        <h4>Add family members</h4>
        <p>Your current family members are:
           {% for member in family.member_set.all %}
           {{ member.profile.user.get_full_name }}{% if not forloop.last %}, {% endif %}
           {% endfor %}
        </p>
        {{ user_formset.management_form }}
        {% for user_form in user_formset.forms %}
        <table class="users_form">
          {{ user_form }}
        </table>
        {% endfor %}
        
        <p class="quiet">To add more family members save and continue editing.</p>
      <input type="submit" name="submit" value="submit" />
    </div>
  </form>
{% endblock %}

{% block rightrailcontent %}{% load tagging_tags %}{{ block.super }}
  {% tags_for_object family as tag_list %}
  {% if tag_list %}
  <h2>Related tags:</h2>
  <p class="inline_tag_list">
  {% for tag in tag_list %}
  <a href="{{ tag|slugify }}/">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
  {% endfor %}
  </p>
  {% endif %}
{% endblock %}